name: Go
on: push
env:
  GO111MODULE: on
  GOPATH: /home/runner/go
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
        - '1.18'
        - '1.19'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: |
        mkdir -p $PATH/src/github.com/xgfone/go-apiserver
        cp -r ./* $PATH/src/github.com/xgfone/go-apiserver
        cd $PATH/src/github.com/xgfone/go-apiserver
        go test -cover -race ./...
